import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  landingPageContainer: {
    width: "100%",
    backgroundColor: "#cfcfcf",
    minHeight: 250,
    maxWidth: 1500,
    alignSelf: "center",
    marginBottom: 20,
  },
  BgImageContainer: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
  },
  landingSchlsListContainer: {
    backgroundColor: "rgba(243, 229, 229, 0.4)",
    paddingHorizontal: 15,
    paddingVertical: 5,
    maxWidth: 400,
    marginLeft: 10,
    position: "absolute",
    bottom: "5%",
  },
  landingListText: {
    color: "#cfcfcf",
  },
  landingUniText: {
    fontSize: 12,
    color: "#000",
    fontWeight: "700",
  },
  landingSearchContainer: {
    alignSelf: "center",
    width: "100%",
    gap: 20,
    position: "absolute",
    zIndex: 100,
    top: 50,
  },
  landingSearch: {
    height: 46,
    width: "80%",
    backgroundColor: "rgba(154, 175, 239, 0.6)",
    borderRadius: 10,
    alignSelf: "center",
  },
  landingTextContainer: {
    alignContent: "center",
    justifyContent: "center",
    width: "auto",
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: "center",
    zIndex: 1000,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  landingText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  landingSearchInput: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
    color: "#777",
    fontSize: 18,
    fontWeight: "400",
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "gold",
    paddingHorizontal: 5,
  },
  webLogoContainer: {
    width: "100%",
    alignSelf: "center",
    justifyContent: "center",
    display: "flex",
    // flexDirection: "row",
    paddingHorizontal: 20,
  },
  webandLogo: {
    flexDirection: "row",
    display: "row",
    gap: 10,
    alignContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
    maxWidth: 230,
    minWidth: 70,
    maxHeight: 50,
  },
  webLogoImgCont: {
    width: 50,
    height: 50,
    backgroundColor: "rgba(247, 231, 231, 0.3)",
  },
  webLogoImg: {
    width: "100%",
    height: "100%",
  },
  logoText: {
    fontSize: 20,
    color: "#cfcfcf",
    fontWeight: "900",
  },
  headerContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  webMenuMainContainer: {
    display: "flex",
    width: "90%",
    maxWidth: 800,
    alignSelf: "flex-start",
  },
  webMenuBody: {
    width: "45%",
    alignSelf: "center",
    alignItems: "center",
    gap: 20,
  },
  closeContainer: {
    position: "absolute",
    top: 30,
    right: 30,
    width: 40,
    height: 40,
  },
  closeImage: {
    width: "100%",
    height: "100%",
  },
  SearchedCoursesModalCont: {
    maxWidth: 1200,
    alignSelf: "center",
    width: "100%",
  },
  SearchedCoursesModalSubCont: {
    marginTop: 70,
  },
  SearchedCoursesContainer: {
    width: "98%",
    height: "auto",
    paddingVertical: 20,
    paddingHorizontal: 5,
    alignSelf: "center",
    marginTop: 30,
  },
  SearchedCoursesHeadContainer: {
    gap: 40,
    width: "90%",
    alignSelf: "center",
  },
  recentSearchesContainer: {
    gap: 10,
    width: "100%",
  },
  recentSearchesHeadContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "80%",
    alignSelf: "center",
  },
  recentSearchesBodySubContainer: {
    gap: 10,
  },
  recentSearchesHeadText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#333",
  },
  recentSearchesClearText: {
    fontSize: 13,
    fontWeight: "600",
    fontStyle: "italic",
  },
  recentSearchesBodyContainer: {
    paddingLeft: 10,
  },
  recentSearchesBodyText: {
    fontSize: 16,
    fontWeight: "400",
  },
});

export default styles;
