import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  landingPageContainer: {
    width: "100%",
    backgroundColor: "#cfcfcf",
    minHeight: 250,
    maxWidth: 1500,
    alignSelf: "center",
    marginBottom: 20,
  },
  BgImageContainer: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
  },
  landingContainer: {
    alignContent: "center",
    justifyContent: "flex-end",
    width: "100%",
    height: "100%",
  },
  landingSubContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    gap: 9,
    paddingHorizontal: 5,
    paddingVertical: 9,
    justifyContent: "space-around",
  },
  landingListContainer: {
    width: "auto",
    display: "flex",
    flexDirection: "row",
    gap: 9,
    alignItems: "center",
    marginHorizontal: 10,
  },
  landingSchlsListContainer: {
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingHorizontal: 15,
    paddingVertical: 5,
    maxWidth: 400,
  },
  landingListText: {
    color: "#cfcfcf",
  },
  landingUniText: {
    fontSize: 12,
    color: "#fcfcfc",
    fontWeight: "700",
  },
  landingSearchContainer: {
    alignSelf: "center",
    width: "100%",
    gap: 20,
    position: "absolute",
    zIndex: 100,
    top: 50,
  },
  landingSearch: {
    height: 46,
    width: "80%",
    backgroundColor: "rgba(169, 177, 179, 0.91)",
    borderRadius: 10,
    alignSelf: "center",
  },
  landingTextContainer: {
    alignContent: "center",
    justifyContent: "center",
    width: "auto",
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: "center",
    zIndex: 1000,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  landingText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  landingSearchInput: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
    color: "#333",
    fontSize: 16,
    fontWeight: "600",
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "gold",
  },
  webLogoContainer: {
    width: "100%",
    alignSelf: "center",
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
    paddingHorizontal: 20,
  },
  webandLogo: {
    flexDirection: "row",
    display: "row",
    gap: 10,
    alignContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
    width: "auto",
    minWidth: 70,
    maxHeight: 50,
  },
  webLogoImgCont: {
    width: 50,
    height: 50,
    backgroundColor: "rgba(247, 231, 231, 0.3)",
  },
  webLogoImg: {
    width: "100%",
    height: "100%",
  },
  logoText: {
    fontSize: 20,
    color: "#cfcfcf",
    fontWeight: "900",
  },
  headerContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  webMenuMainContainer: {
    display: "flex",
    width: "90%",
    maxWidth: 800,
    alignSelf: "flex-start",
  },
  webMenuBody: {
    width: "45%",
    alignSelf: "center",
    alignItems: "center",
    gap: 20,
  },
});

export default styles;
