import { StyleSheet } from "react-native";

const style = StyleSheet.create({
  updatesMainContainer: {
    // flex: 1,
    backgroundColor: "#e7d9d9ff",
    maxWidth: 1300,
    alignSelf: "center",
  },
  updatesHeadMainContainer: {
    width: "100%",
    maxWidth: 1000,
    minHeight: 250,
    alignSelf: "center",
  },
  updatesHeaderContainer: {
    width: "100%",
    maxWidth: 1000,
    minHeight: 250,
    backgroundColor: "#fff",
    alignSelf: "center",
    paddingVertical: 30,
  },
  updatesHeaderImageContainer: {
    width: "100%",
    height: "70%",
    alignItems: "center",
  },
  updatesHeaderImage: {
    width: "100%",
    height: "100%",
  },
  updatesHeaderTextContainer: {
    width: "95%",
    paddingTop: 15,
    alignSelf: "center",
    gap: 10,
  },
  updatesHeaderText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#555",
  },
  updatesHeaderDate: {
    fontStyle: "italic",
    fontSize: 14,
    paddingLeft: 20,
    fontWeight: "500",
    color: "#000",
  },
  updatesContainer: {
    marginBottom: 50,
    gap: 20,
  },
  updatesMainBodyContainer: {
    width: "100%",
    paddingVertical: 10,
    alignSelf: "flex-start",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginBottom: 30,
  },
  updatesListContainer: {
    width: "95%",
    maxWidth: 1000,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  updatesListSubContainer: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    paddingVertical: 10,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  updatesListImageContainer: {
    width: 15,
    height: 15,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  updatesListImage: {
    width: "100%",
    height: "100%",
  },
  updatesListTextContainer: {
    width: "auto",
    height: "auto",
  },
  updatesListText: {
    fontSize: 14,
    color: "#333",
    fontWeight: "600",
    textAlign: "left",
    fontStyle: "italic",
    flexShrink: 1,
    flexWrap: "wrap",
  },
  newsMenuMainContainer: {
    flex: 1,
    padding: 20,
    maxWidth: 1400,
    width: "95%",
    alignSelf: "center",
    backgroundColor: "rgba(245, 199, 199, 0.7)",
    marginVertical: 15,
  },
  newsMenuContainer: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 1000,
    backgroundColor: "rgba(248, 241, 241, 0.5)",
    padding: 10,
    borderRadius: 50,
    width: 50,
    height: 50,
  },
  newsMenu: {
    width: "100%",
    height: "100%",
  },
  NewsBodyContainer: {
    width: "100%",
    alignSelf: "center",
    paddingTop: 50,
  },
  NewsBodyHeaderContainer: {
    width: "88%",
    alignSelf: "center",
    paddingVertical: 10,
    gap: 15,
  },
  NewsBodyHeaderTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#444",
    textAlign: "left",
    paddingBottom: 10,
  },
  date: {
    fontSize: 12,
    fontStyle: "italic",
    color: "#333",
    textAlign: "left",
    fontWeight: "700",
    marginLeft: 20,
  },
  NewsBodyImageContainer: {
    width:'100%',
    maxWidth: '1000',
    overflow: "hidden",
    marginTop: 10,
    backgroundColor: "#rgba(148, 186, 239, 0.8)",
  },
  NewsBodyImage: {
    width: "100%",
    height: "100%",
  },
  socialMediaBTNContainer: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "10",
    marginTop: 20,
    alignSelf: "center",
    backgroundColor: " rgba(255, 255, 255, 0.8)",
    padding: 10,
  },
  socialMediaBTN: {
    width: 30,
    height: 30,
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
  },
  socialIcon: {
    width: "100%",
    height: "100%",
  },
});

export default style;
